# 配置文件

DAILY_TIME: "07:30" # 每日定时发送时间。该时间为系统时间，如果当前系统时间不为北京时间需要自行进行换算

START_DATE: "2020-01-08" # 纪念日
CITY: "简阳"

BIRTHDAY:
  - "11-16"

APP_ID: "wxd430aa7b8dcfd787"
APP_SECRET: "010184a1fb49baf28eb2d14cca141732"

USER_ID: 
  - "oKQRR5xFIO5Ddp_I7pYZ_L8fR9BQ"
  - "5i4TCbHZpp4XuW_FJsjDH4-mqJyR7fJ1iBc1p82xKho" # 你可以通过配置多个USER_ID来设置多个接受者，如果接受者只有一人删除本行即可
TEMPLATE_ID: "	5i4TCbHZpp4XuW_FJsjDH4-mqJyR7fJ1iBc1p82xKho"
